### ISSUE TITLE
Is there a typo in line 11?

### ISSUE THREAD

**Issue by JMA6971** [Aidlab/aidlab-python-examples#2]
https://github.com/Aidlab/aidlab-python-examples/blob/e8e8db3a59488ae1f72b0fed3c2c26397e798a08/Aidlab/data.py#L11

**Comment by Szymon-Gesicki** [comment]
Can you paste exact problem you are encountering here?

**Comment by JMA6971** [comment]
it's been too long and I haven't looked since... I believe the problem was something about the code referencing the directory structure incorrectly

**Comment by Guziq** [comment]
I am closing it now as we've made some improvements here. Feel free to reopen this issue if the problem will happen again.
