### ISSUE TITLE
ModuleNotFoundError: No module named 'Aidlab.Signal'

### ISSUE THREAD

**Issue by Bahar1978** [Aidlab/aidlab-python-examples#5]
Dear,
While practicing "basic-sleep-detector.py" from https://www.aidlab.com/blog/basic-sleep-detector-in-python, I received de following error:
ModuleNotFoundError: No module named 'Aidlab.Signal'

Could you please check this?

**Comment by Szymon-Gesicki** [comment]
This has been corrected in version 1.3.24
