### ISSUE TITLE
did_disconnect

### ISSUE THREAD

**Issue by Bahar1978** [Aidlab/aidlab-python-examples#6]
I have another issue working the basic example:
I can see the message "Connected to:  some numbers"
But when I disconnect the device for example turn it off de device or stop my belututhfrom my computer, then I except to see the message ""Disconnected from: ", some numbers" , but it still scanning.
Could you please check it and let me know if I need to change some definitions?

**Comment by Szymon-Gesicki** [comment]
Hi, does this still occur in the latest version? If so, please provide information on what system you are using and what version of AidlabSDK?
