### ISSUE TITLE
several time scanning

### ISSUE THREAD

**Issue by Bahar1978** [Aidlab/aidlab-python-examples#7]
Dear,
When I use your all python examples, I see that after connecting to the device, it keeps scanning, does it mean that it is disconnected?
For example:
Scanning ..........
Scanning ..........
Connected to:  "device number"
Scanning ..........

Thanks in advance

**Comment by Szymon-Gesicki** [comment]
This is explained in the documentation. [aidlab.com](https://www.aidlab.com/developer/docs/python.html)

```
The connect function expects two parameters:
signals - an array of signals you would like to listen to. List of the available signals.
addresses - an optional parameter which you can use if you know the address(es) of the Aidlab(s) you'd like to connect to. If it is empty Aidlab SDK will try to connect to all nearby devices. After disconnecting it will start scan again. If addresses is not empty, there will be only one attempt to connect to the selected devices.
```
